### ISSUE TITLE
support new actions during interactive learning

### ISSUE THREAD

**Issue by amn41** [RasaHQ/rasa_core#1184]
It would be great to support creating new actions during interactive learning. The user would come up with the new action on the spot, but would have to back later and ensure there is a template defined (for utter actions) or there is a custom action registered at the appropriate endpoint.

**Comment by tarunbhavnani** [comment]
whenever i tell interactive learning for a new actions it does this:
? What is the next action of the bot?  0.02 family_form                         
? Do you want to stop?  Continue
? Export stories to (if file exists, this will append the stories)  data/stories
.md
? Export NLU data to (if file exists, this will merge learned data with previous
 training examples)  data/nlu.md
? Export domain file to (if file exists, this will be overwritten)  domain.yml
? Could not load existing NLU data, please specify where to store NLU data learn
ed in this session (this will overwrite any existing file)  data/nlu_interactive
.md
then the same happens again and again
How should i train it for a new action

**Comment by amn41** [comment]
I'm not sure what's happening in your case. Can you please create an issue? Please include the version you are running, your domain file, and steps to reproduce.

**Comment by josebrwn** [comment]
> ? Export NLU data to (if file exists, this will merge learned data with previous
> training examples) data/nlu.md
> ? Export domain file to (if file exists, this will be overwritten) domain.yml
> ? Could not load existing NLU data, please specify where to store NLU data learn
> ed in this session (this will overwrite any existing file) data/nlu_interactive
> .md

Same thing happens to us. What is the purpose of saving the NLU data twice, to different files? What is the difference between "learned data" and "data learned in this session"? Why in the first save does it save an empty file every time (rather than merging)? Why can't the agent find the nlu.md file that it's been using all along? Why does the first save create an empty file, and the second save create a file consisting solely of the new session?
