### ISSUE TITLE
Docs on how to build a bot with rasa & docker

### ISSUE THREAD

**Issue by tmbo** [RasaHQ/rasa_core#1239]
We do have some docks about the docker installation process, but there isn't a lot of information around the whole development process.

Idea: Have a walk through of the development with docker and the different steps involved in the creation of the chatbot:
- setup
- adding training data (nlu and core, creating a domain, mounting this)
- adding code (custom python code for actions using the sdk, maybe even including custom dependencies, so other python libraries that need to be installed )
- running it
- connecting it to a platform (facebook, ...)

**Comment by tmbo** [comment]
@JustinaPetr do the above steps make sense, should we change the order?

**Comment by tmbo** [comment]
I mean, I like to start from scratch, but I am not the model user for this - so better if @JustinaPetr takes a guess.

**Comment by jonDel** [comment]
How about an example using a docker compose file, in order to run all the containers integrated as one service (rasa core, rasa nlu, sdk - actions, the tracker store, etc)?

**Comment by JustinaPetr** [comment]
@tmbo @wochinge I think the steps above make sense. It's good to show the step-by-step process from scratch because it's important to enable anyone - from complete beginner to an experience Docker user to be able to follow.
Also, I think that starting from scratch is an easier way to explain the entire process step-by-step. So I guess reusing the data of the starterpack and the idea of the bot would still be ok, but I would go through the development process step-by-step from the very beginning.
