### ISSUE TITLE
Feature request: Allow passing dynamic timezone to duckling

### ISSUE THREAD

**Issue by alexmic** [RasaHQ/rasa_core#1442]
**Rasa Core version**: 0.11.12

Suppose we have a customer in Berlin (UTC+1) and we allow them to ask the following two questions:
1. "How much have I spent 2 hours ago?"
2. "How much have I spent between 15:00 and 16:00?"

If we configure duckling to always use UTC and the customer asks that question at 18:00, question 1 will return the correct time back (15:00 UTC, 16:00 UTC+1) but question 2 will return 15:00 UTC - 16:00 UTC, which is wrong because the customer means UTC+1. 

Ducking allows `tz` on `/parse` requests which we can use to get the correct result back so is it a good idea to allow request-level component config to rasa core?

**Comment by wochinge** [comment]
@alexmic 

I think there are two problems at the moment. 
Number 1 is that Duckling does not currently not actually use specified timezones (see https://duckling.wit.ai/ , Limitations)

> Timezones are parsed, but they don’t impact the time value (will be fixed shortly).

The second thing is, that you want to use different time zones depending on the user, right?
I think this is best done using custom actions since Rasa Core does not know the location of the user. In the custom action you can check the whether you know the location of the user, and then select the correct timezone.
