### ISSUE TITLE
Sending Intent with message like dialogflow

### ISSUE THREAD

**Issue by stacybot123** [RasaHQ/rasa_core#1522]
**Rasa Core version**: 0.13.X

**Python version**: 3.6

**Operating system** (windows, osx, ...): ubantu 18.04.1

**Issue**:
Can we send intent with the response message, like dialogflow. For example with the utter_message it will also say the intent also. Like below

```
[
    {
        "recipient_id": "123456789",
        "text": "Hello! How can I help?",
        "intent": "greet",
    }
]
```

**Comment by bikashkumars** [comment]
I have some out-of-box answer for your question. I assume you are running rasa core server and usually it returns "recipient_id" and "text". Because internally it handles dialog, NLU.

To get more information related to intent and entity, i would recommend you following

1. Run Rasa NLU server
2. Run Rasa NLU server on custom port (Usually it runs on port 5000 as default)

The following command will run, Rasa NLU server on port 3000
python -m rasa_nlu.server --path projects - P 3000

Make request to following with body of user typed text as "hi"
URL:     http://localhost:3000/parse
Body:    { "q":"hi" }

Response will be 
{
    "intent": {
        "name": "greet",
        "confidence": 1
    },
    "entities": [],
    "text": "hi",
    "project": "default",
    "model": "fallback"
}

Then you can get intent and entity.

**Comment by stacybot123** [comment]
@bikashkumars  thanks for the reply , I noticed that before ,  using the above endpoint , there will be two calls to the server for every message the user will be entering in the chat

**Comment by akelad** [comment]
can we close this issue or is your question still unanswered?

**Comment by stacybot123** [comment]
Yes, if we cannot return the intent with the message from core.
