### ISSUE TITLE
Story block processing much slower in 0.8.1 compared to 0.7.9

### ISSUE THREAD

**Issue by Timsey** [RasaHQ/rasa_core#210]
**Rasa Core version**: 0.7.9 and 0.8.1

**Python version**: 3.5.2

**Operating system**: Ubuntu 16.04

**Issue**: It seems story block processing is much slower on the same data in version 0.8.1 compared to 0.7.9. This data makes heavy use of checkpoints, so my suspicion is that something in the new support for story cycles causes this behaviour. Compare:

0.7.9
![core 0 7 9 dialogue training](https://user-images.githubusercontent.com/35295146/35807556-6547d542-0a83-11e8-8e06-044e7f4bea64.png)

0.8.1
![core 0 8 1 dialogue training](https://user-images.githubusercontent.com/35295146/35807558-67c26efe-0a83-11e8-8f33-c70f602ce1f4.png)

The first phase is very similar between versions, after which we see a ~9 times slowdown in phases 2-4. Is this a fundamental limitation of the new generation method?

**Comment by znat** [comment]
I am observing the same, with much less stories. 3 secs/it 
![capture d ecran 2018-02-07 a 18 07 02](https://user-images.githubusercontent.com/3694634/35946461-d9122838-0c31-11e8-99d8-85879ce4a7e5.png)

**Comment by tmbo** [comment]
Mhm, I don't think there is an inherent reason for that. But I'd need to take a closer look at this. @znat do you mind sharing that dataset with me?

**Comment by znat** [comment]
So my previous comment was irrelevant because I was on 0.8.04a with an old laptop.
Now that I am with a brand new i7 quad core on 0.8.2 I can clearly see a difference in the speed story blocks are processed.
<img width="797" alt="capture d ecran 2018-02-17 a 16 30 38" src="https://user-images.githubusercontent.com/3694634/36345841-a93f5d84-1400-11e8-9235-12d1c9eab3a3.png">
It just hangs. 

This is the commit where it starts: https://github.com/RasaHQ/rasa_core/commit/5a0f0ea445da8f6cbfe53402aa70b1900fd23f66

**Comment by znat** [comment]
Digging further, my checkpoints were creating an exponentially increasing number of stories.  So probably no issue on the Core side after all,

**Comment by tmbo** [comment]
Oh that is an interesting point - how did you debug that?
