### ISSUE TITLE
Add Pytorch as deep learning framework backend in policies and rasa_nlu

### ISSUE THREAD

**Issue by walkacross** [RasaHQ/rasa_core#267]
Hey, thanks for your great projects. May I have a few suggestions for this great program?

(1) Add Pytorch(https://github.com/pytorch/pytorch) as one of the deep learning backend.

Considering Pytorch is much more pythonic and popular,  Is there a roadmap to add Pytorch as ome of the deep learning backend in policy  and Rasa_NLU.

(2) Considering  that Rasa Core is a framework, why not support custom training process in RASA_NLU, which is familiar with custom policies.

(3) Is there any plan to support Chinese language in this nice project?

Thanks for your time and have a good day.

**Comment by tmbo** [comment]
thanks a lot for your suggestions.

at the moment there are no plans to implement a pytorch policy. we usually implement new policies only if there is a new method that has a benefit, not just because we want to use a different underlying library. but of course we are very happy to accept contributions.

I am not sure I understand the custom training you are looking for. Can you explain in more detail what you mean?

Chinese support would fall more into the nlu part, and there has been done some work on it, but I don't know if there is something ready yet.

**Comment by walkacross** [comment]
hey tmbo, thanks for your kind reply and glad to hear that Chinese support would fall into RASA_NLU.

In suggestion 2, I mean, is there any possibility that Rasa_NLU provides a more flexible parent classifier which user can subclass, and then train more advanced classifier for intent detection (not only the predifned SVM algo).

Again, thanks for your great project, have a nice day.
