### ISSUE TITLE
Slack Restaurant Bot replied 12 times when I say hi

### ISSUE THREAD

**Issue by Tenglu** [RasaHQ/rasa_core#304]
**Rasa Core version**: 0.8.5

**Python version**:  Python 3.6

**Operating system** (windows, osx, ...): Windows 10

**Issue**:
When I said "hi" to restaurant bot provided in examples, it replied 12 times.  Is it the normal case? I think it may be because 12 stories are matched when I say hi?

![capture](https://user-images.githubusercontent.com/8437103/37863802-53185a22-2f9f-11e8-85c9-10105c1a9f1a.PNG)

**Content of domain file** (if used & relevant):
```yaml

```

**Comment by tiwari85aman** [comment]
@Tenglu I also had this issue when I was working with slack, maybe this issue was because of slack connection which is sending some sort of connection messages to your webhook, and rasa bot is taking this as the messages to be processed and hence replying for something not desired.... 
However, telegram integration works fine and no such issue was seen ...

**Comment by akelad** [comment]
@Tenglu could you share your stories file?

**Comment by Tenglu** [comment]
@akelad  I used the same stories file as Restaurant Bot example.

**Comment by akelad** [comment]
it seems more people are having this issue #384 so we'll look into it

**Comment by NikhilBansal21** [comment]
How soon can we know the real cause for this issue, cz i think maybe this issue is being caused due to ngrok because on running bot locally in cmd this is not happening. But i am not sure that this the only reason for the issue.

**Comment by tiwari85aman** [comment]
it's not the issue with ngrok because I have also tried tunneling with Pagekite as well. this is the issue with the slack connection because if you look closely on the localhost page of ngrok you will find that slack repeatedly sends some responses to our bot which I think are treated as messages by the bot, however they are not the user messages they are some sort of connection acknowledgment.

**Comment by akelad** [comment]
Hey guys, so I've finally gotten round to looking into this and i'm pretty sure it's not a slack problem. this happens even on the command line if you say hi multiple times. the stories in this example have a very strict path, and so will behave unexpectedly when not following that path. basically you need to add more stories to it if you want it to behave better. when running on the command line, you can run the bot with the ``--debug`` flag to see what actions the bot is predicting with what probablity etc.
I'll close this issue for now, but let me know if you're still having issues.
