### ISSUE TITLE
Chat Bot response issue

### ISSUE THREAD

**Issue by Selvaganapathi06** [RasaHQ/rasa_core#306]
1) I have built a bot based on restaurant bot example and i have integrated bot in my own ui page. what are all the things i need to check before using my bot in live environment.

2) My bot is working fine but sometimes it is not working properly.it gives inconsistent results how to overcome this.
 
3) i have set a default response for untrained questions by some conditions like confidence score < 0.4 as mentioned in rasa core issue no 137.
confidence score of some untrained questions is high and trained words is low . how to increase confidence score.can you explain, in which basis confidence score is working? if i set default response with low confidence some trained words also not getting the response.do you have any idea about this?

**Comment by akelad** [comment]
1) We advise that you test your bot thoroughly just by talking to it and especially getting others to talk to it as well to ensure it behaves correctly
2) I’m not sure what inconsistent results you’re having, but if they’re NLU related then the solution is to add more training data, and if it’s Core related, then you need to add more stories.
3) The confidence score is best increased with adding more training data as well. Also you should check that you’re using the medium spacy model rather than the small one, because this gives better results.
