### ISSUE TITLE
Ignore intent classification during form filling

### ISSUE THREAD

**Issue by mtbikerj** [RasaHQ/rasa_core#310]
**Rasa Core version**:
0.8.4

**Python version**: 
3.5.4 

**Operating system** (windows, osx, ...):
Windows 10

**Issue**:
This is an enhancement request.  

There are situations in bot conversations that require some generic responses that simply can't be handled by an NLU processor.  Situations were we just need to collect data in a pre-determined manner to fill empty or missing slot values.

There are times where we might need to collect a number or random text from the input channel and push that information directly into a slot bypassing the interpreter and prediction of next action.

Example:  Collecting a user name and password
... stop tracker and issue data collection action ...
Bot:  What's the username?
User: JimmyJimmy123 (or some other text that cannot be easily categorized or featurized by NLU)
Bot: What's the password?
User: 194aampass10238
... restart tracker ...

Example 2: Collecting a unique name for something
Bot:  What do you want to name your widget
User: My awesome widget that can do everything

in this case, the entire string should be captured, regardless of whether a user inputs anything that the NLU would recognize as an intent.  They could enter "hello" or "reset" and we wouldn't want to translate that as an intent because the context we are in is asking for information (or a custom action).

**Comment by amn41** [comment]
does https://github.com/RasaHQ/rasa_core/pull/261 do what you need?

**Comment by mtbikerj** [comment]
Yes, that would work.  Sorry I didn't see that one.

**Comment by AbdurRub** [comment]
when should we expect merging of this feature? @amn41

**Comment by mtbikerj** [comment]
@AbdurRub - I think you want to ask this question on the #261 thread.  This one is a duplicate because #261 will meet that need.

**Comment by tmbo** [comment]
I'll reopen this one, because even the form filling won't solve this: the form filling is just a shortcut making it easier for the classifier to pick the right action *within* the form. What I mean is, that by adding the form filling, the model does not need to exactly predict where we are in terms of the form filling task (e.g. which field needs to be filled next), it just needs to predict that we are within that form.

*BUT* if the user e.g. inputs `hello` and the intent will be `greet` the model will still run `action_greet` after that input and not the form action. Just because during the training it saw the action greet getting predicted after that intent.

**Comment by amn41** [comment]
yes @tmbo you are right - I also think we shouldn't just ignore intent altogether if you are in the form, because you should absolutely be able to say something to 'break free' of the form and not just get stuck in a loop :) as I see it this is an NLU problem where we need to have better support for a generic "entering information" intent. 

currently if your 'entering information' messages get misclassified as 2-3 different intents by NLU then you should just add all of those as stories. That's better than just a blanket 'ignore nlu' policy

**Comment by ExarchD** [comment]
Is there any update on this?

**Comment by amn41** [comment]
forms v2 (released in rasa core 0.12 solves this, see [here](https://www.rasa.com/docs/core/slotfilling/)
