### ISSUE TITLE
Interactive Learning vs Running from console Issue

### ISSUE THREAD

**Issue by AbdurRub** [RasaHQ/rasa_core#331]
**Rasa Core version**: 0.8.4

**Python version**:  2.7

**Operating system** (windows, osx, ...): Ubuntu 17.10

**Issue**:
I just observed that output/action I am getting with interactive learning is different than when I train that dialogue and run from console. running from console gives too some extent right action. But different action thing is strange , why is this so.

**Comment by akelad** [comment]
Are the stories you're trying in your training data? Or are they unseen? Because if they're unseen, then Keras doesn't necessarily always predict the same action each time it's trained

**Comment by AbdurRub** [comment]
You can say so its unseen because I just queried what comes in my mind. it can or cant be in training data. 
But I tried 2 times from console and from interactive learning. its giving same different actions. 
correct one in case of console and wrong one in case of interactive learning.

**Comment by akelad** [comment]
Right, but can you check whether it's in the stories file or not? And also enabling debug mode should help, then it will tell you whether it's predicted with the MemoizationPolicy or the KerasPolicy. Because if it's being predicted with KerasPolicy for both the console and interactive learning, then as I said this will not be consistent every time you retrain a model.

**Comment by AbdurRub** [comment]
Ok.  Can you just give me short difference between memorization policy and keras policy?

**Comment by akelad** [comment]
Basically the MemoizationPolicy "memorises" your training data, and the KerasPolicy uses machine learning to predict actions for unseen data. More here: https://core.rasa.com/policies.html

**Comment by AbdurRub** [comment]
Thanks @akelad!
