### ISSUE TITLE
Configure path to export stories to after online lerning

### ISSUE THREAD

**Issue by deviantdes** [RasaHQ/rasa_core#39]
**Rasa Core version** (e.g. `0.7.3`):
0.7.1
**Operating system** (windows, osx, ...):
Windows 10
**Issue**:
Hi there
For this example in https://core.rasa.ai/tutorial_fake_user.html , Where do i set the story path for exporting ?
the action for `0.Export current conversations as stories and quit`

i tried exporting but there don't seems to have any stories created.

Thanks in advance
**Content of domain file** (if used & relevant):
```yaml

```

**Comment by kianmeng-aft** [comment]
the default location is at root `/debug.md` , but i am also looking if this path is configurable

**Comment by deviantdes** [comment]
@kianmeng-aft  Oh Thanks ! Issued resolved and closed.

**Comment by tmbo** [comment]
I'll keep this open as there ideally should be a way to specify where to store the stories.

**Comment by tmbo** [comment]
Can be configured now, user is asked for the filename after the interactive learning session ended.

**Comment by rojobuffalo** [comment]
In the examples you put your stories in `data/stories.md`. To stick with that convention I'm having to type `data/stories.md` every time to export, bc if I just hit <enter> it will write to `/stories.md`. Is there a way to get that to go to `data/stories.md` as a default so I can just hit <enter> button?

**Comment by rojobuffalo** [comment]
Also, when I've completed a conversation turn and the bot is listening and I want to export the conversation, I'm typing `0`, then it prompts me for feedback where I again type `0`, before it realizes I'm ready to export. So the last conversation turn that gets exported includes this `0` intent and the `- export` action:

#### `stories.md`
```
## Generated Story 4356574900147059196
* greet
    - utter_greet
* commands
    - utter_commands
* 0
    - export
```

This then causes an error when I run `train_online` the next time because:
```
rasa_core.featurizers - Couldn't set most probable feature 'intent_0', it wasn't found in the feature list of the domain. Make sure you added all intents and entities to the domain.
```

So I'm going in and deleting that last line every time I rewrite/export. Should I be doing something different?

**Comment by rojobuffalo** [comment]
Hope I'm not polluting the issue tracker with this, but I'm also getting weird behavior with output that is specified to be placed in `data/stories.md` but is ending up in `/stories`, not from online training but the regular train script (taken verbatim from examples/concertbot).

#### `train.py`
```
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals

from rasa_core import utils
from rasa_core.agent import Agent
from rasa_core.policies.keras_policy import KerasPolicy
from rasa_core.policies.memoization import MemoizationPolicy

if __name__ == '__main__':
    utils.configure_colored_logging(loglevel="INFO")

    training_data_file = 'data/stories.md'
    model_path = 'models/dialogue'

    agent = Agent("mybot_domain.yml",
                  policies=[MemoizationPolicy(), KerasPolicy()])

    agent.train(
            training_data_file,
            augmentation_factor=50,
            max_history=2,
            epochs=500,
            batch_size=10,
            validation_split=0.2
    )

    agent.persist(model_path)
```

When I run this it writes to a file `/stories.md` instead of appending to `data/stories.md`. Is that how it's supposed to behave?

**Comment by amn41** [comment]
yes that's the correct behaviour - the 'training data file' arg is what's used for initial training. you still have to decide explicitly which exported stories you want to include in that

**Comment by rojobuffalo** [comment]
thanks for clarifying. so when you run `train.py` there is not a way to tell it where to write that file (without modifying your installation of rasa_core)? It will always write to `/stories.md` and then it's up to you to merge that with the stories doc you will use as a training base for subsequent training?
