### ISSUE TITLE
User input in custom action script

### ISSUE THREAD

**Issue by Priprocks** [RasaHQ/rasa_core#533]
**Rasa Core version**:
0.9.0a3
**Python version**: 
3.6.5
**Operating system** (windows, osx, ...):
Windows 10
**Issue**:
I am finding difficulties in making a custom action where I can break free from normal user-rasa processing-bot flow and can ask for certain inputs directly.
I mean I don't want another intent to ask a follow up question (for example, Booking time), I should be able to directly input it in my custom action script.
There is formfilling option but it would be great if I can take over the flow and communicate with the user directly.
For example, I want a password or any information of that kind, I need to use
```
getpass.getpass()
```
for getting it but there is no way to do that using formfilling

Please help me out if I am missing something.
If it can't be done, I'll be happy to work on this enhancement!

**Content of domain file** (if used & relevant):
```yaml

```

**Comment by auzair92** [comment]
I am looking for something similar. In my use case, I have an additional REST service (let's call it `SymptomsService`) which provides questions to be asked from the user. It is sort of like a service within service (`SymptomsService` within Rasa service).

Explanation: Using Rasa's conversation flow, when I reach a certain point in conversation, I want a method to take over and handle the Q&A with the user, something like:
```
* greet
- utter_greet
- utter_how_may_i_help
* i_am_sick
- action_get_symptoms
```
This `action_get_symptoms` action is dependent on the additional REST service, `SymptomsService`. I cannot implement it directly in Rasa conversation flow since it is already built, a flow of multiple questions has been formed, and only needs to be presented to the user, and their answers need to be returned to the `SymptomsService` so that a symptoms statement may be generated.

The reason I cannot use Rasa's `FormAction` class is that this Q&A flow is context dependent itself. Question 2 coming from `SymptomsServer` might be different according to the input provided as answer of Question 1, and `FormAction`'s required fields don't work in that way.

As an example, the flow of this Q&A with `SymptomsService` might go like:
```
Q1: Enter any symptoms that you are feeling:
Answer: Flu and fever
Q2: Have you tried any medication?
Answer: Yes (or No)
Q3: (If previous answer was Yes) Enter the medicine name.
(If previous answer was No, service will skip this question and move on to Q4).
Q4: ...
```
This is essentially like filling out a form, and has been converted to conversational format in my separate `SymptomsService`, I just need to integrate it within Rasa flow.

I would appreciate any feedback on this.

**Comment by Priprocks** [comment]
Exactly! This would be a much needed enhancement. Sometimes, it is required to communicate with the user beyond the RASA flow and currently there is no way to do that.

**Comment by tmbo** [comment]
This is a very good point and a good enhancement. I'll think about it as well :+1:

**Comment by amn41** [comment]
couldn't you do this by sending a `ConversationPaused` and then `ConversationResumed` event?

**Comment by auzair92** [comment]
@amn41 Could you please elaborate this, perhaps using a simple example? The functionality of these events isn't quite clear to me looking at the docs only.

**Comment by amn41** [comment]
sure - if your action returns a `ConversationPaused` event, Rasa Core will not take any action when it receives new messages, until a `ConversationResumed` event is triggered. This allows you to take over the handling elsewhere without Rasa Core interfering

**Comment by tarunbhavnani** [comment]
@amn41 a basic example for this would help. Like for confirming a name using fuzzy logic in the middle of an action or getting a simple yes/no from the user.

**Comment by amn41** [comment]
there is a new version of the forms coming in v0.12 which should do what you need. that will come with examples too :)

**Comment by bodhwani** [comment]
Hey, @amn41  Is the issue solved in the new version?

**Comment by amn41** [comment]
yep! check out this post https://blog.rasa.com/building-contextual-assistants-with-rasa-formaction/

**Comment by akelad** [comment]
@amn41 can this issue be closed then?

**Comment by amn41** [comment]
yes
