### ISSUE TITLE
Question: Further steps of development

### ISSUE THREAD

**Issue by djuelg** [RasaHQ/rasa_core#577]
Hey there,

currently I'm thinking about using rasa core for my bachelor thesis, which will be a prototype of a chatbot. Since rasa core still seems to be in beta I would like to know how development is going further.

* Do you think rasa would already be a good choice to use?
* Are there a lot of breaking changes between versions?
* Do you plan to finish beta in the next couple of weeks/months?

On one hand I fear using rasa core because it could end in tons of breaking changes and missing documentary for old versions and so on. On the other hand I really like it so far and it would be awesome to give it a try :)

**Comment by DhruvMevada** [comment]
Yes, I am using Rasa since 4 months. I have seen many updates in this duration. It's continuously updating. 

Rasa really great tool for developing chatbot rather then going for Tensorflow. Because Rasa is one kind of wrapper of tensorflow. And Its open source we can add modify the library files. 

Also provides good entity extractions  with different NLP library supports.

**Comment by swathy06** [comment]
@DhruvMevada : Are you able to set float values in slot and do mathematical calculations in it?

**Comment by akelad** [comment]
@djuelg so we don't guarantee backwards compatibility (since it's still in version 0.x). However, when there's breaking changes, they're always well documented. You can check out our documentation, there's different ones for each version.
How long is the period of your bachelor thesis? you can always stick to one version if need be :)

**Comment by djuelg** [comment]
@akelad Ah thanks a lot for your answer, that's exactly what I thought. My thesis will be finished at the end of august. I'm convinced and happy to use Rasa now :)

**Comment by tmbo** [comment]
I'll close this for now, please let us know if you have any further questions.
