### ISSUE TITLE
A way to get multiple suggested answers from Rasa bot with confidence scores for each.

### ISSUE THREAD

**Issue by Shehzad777** [RasaHQ/rasa_core#656]
Here is an **enhancement** request.

In one implementation of Rasa chat bot, we need for the bot to suggest top 5 suggested answers based on score / confidence (so obviously also need for the bot to tell us scores / confidence value for each as well).

Thanks.

**Comment by Ghostvv** [comment]
@Shehzad777 In order to do this, you need to subclass `PolicyEnsemble` and overwrite this method: https://github.com/RasaHQ/rasa_core/blob/93101815832cc00dc81d71f6e9d5eccd7f96ca17/rasa_core/policies/ensemble.py#L78

**Comment by Shehzad777** [comment]
Thanks @Ghostvv. Can you please elaborate or help out with this overwriting. Just a high level info would be good enough.

**Comment by Ghostvv** [comment]
@Shehzad777 For example the standard ensemble that is used in `rasa_core` is `SimplePolicyEnsemble`. It subclasses `PolicyEnsemble` and overwrites this method: https://github.com/RasaHQ/rasa_core/blob/7ca2a23473a52d0054bc35052e8ddad13ab2447c/rasa_core/policies/ensemble.py#L209 and return the probabilities from the policy that provide the maximum confidence. Then the action with maximum confidence is picked by https://github.com/RasaHQ/rasa_core/blob/7ca2a23473a52d0054bc35052e8ddad13ab2447c/rasa_core/policies/ensemble.py#L82.

Please take a look at the body of these functions. In your custom class you would need to substitute the logic there with the one that gives what you need.

So in order to pick 5 best actions I would overwrite `probabilities_using_best_policy` to create an array of probabilities with maximum confidences for each action. And then in `predict_next_action` find 5 indices that have maximum confidence.

Please be aware that standard `rasa_core.processor.MessageProcessor` uses only 1 index here: https://github.com/RasaHQ/rasa_core/blob/7ca2a23473a52d0054bc35052e8ddad13ab2447c/rasa_core/processor.py#L405. So you would probably need to change that as well.

Please let me know if you have any questions.

**Comment by Shehzad777** [comment]
Thanks @Ghostvv. I really appreciate it. Let me get back to you if I have any queries.

**Comment by abdulhaleem247** [comment]
@Ghostvv How can I register my custom `PolicyEnsemble` subclass? I mean is it passed as an argument to `agent.load()` or some other function?

**Comment by akelad** [comment]
I'm guessing you had no more questions - so i'll close this issue for now.
