### ISSUE TITLE
Starting a conversation using HTTP Server 

### ISSUE THREAD

**Issue by Rajskc** [RasaHQ/rasa_core#699]
**Rasa Core version 0.9.3**:

**Python version 3.6.5**: 

**windows**:

**Starting a Conversation with Http Server**:

**Content of domain file** (if used & relevant):''

Hello,

I have created a bot using rasa and I want to run it on HTTP Server. The command which I have used to start the sever is: **python -m rasa_core.server -d models/dialogue -u models/nlu/default/creditnlumodel -o out.log** and the code to start the conversation is: **curl -XPOST localhost:5005/conversations/default/parse -d '{"query":"okay"}'**. I am getting a error as shown below:
![image](https://user-images.githubusercontent.com/33925712/42318561-0360e23c-806d-11e8-8a90-fc4b8e6bc2c2.png)

I couldn't understand the detailed functioning of HTTP server from the docs. Can anyone help me with this? Thanks! :)

**Comment by auzair92** [comment]
Have you followed all the instructions given in the [official docs](https://core.rasa.com/http.html)? Are you sure the Rasa server is up and running at the given address and port? Unfortunately I am unable to pin-point the issue without being able to reproduce it, so I can only offer some generic guidelines. 

- You could try sending to the server a different request (a [GET](https://core.rasa.com/http.html#get--conversations-(str-sender_id)-tracker) instead of POST, for example).
- See if you can use an API testing tool (like [Postman](https://www.getpostman.com/)) instead of CURL to send the request.

**Comment by amn41** [comment]
it could be that it's a windows issue with single quotes, try `"{/"query/":/"okay/"}" ` instead

**Comment by Rajskc** [comment]
@auzair92 
I have tried with GET request and the server is responding as shown in image below, but in case of POST command the server is not able to understand the command. The log file is without any errors.
![image](https://user-images.githubusercontent.com/33925712/42432174-f37c48dc-8366-11e8-8373-d28942138f50.png)

If I include **python -mjson.tool** at the end of the command, the result is different and it seems to understand but it is not responding to it. May I know what does this command do here?

**Comment by auzair92** [comment]
If `GET` is working and `POST` is not, then most probably it's an issue with the request itself. @amn41's suggestion above looks appropriate here; you should try that. 

I believe the `-mjson.tool` is simply used to pretty-print the JSON response so that you can easily validate it from the terminal. Whether or not the server responds with an appropriate response is not dependent on this.

**Comment by auzair92** [comment]
Try this command:
`curl -XPOST localhost:5005/conversations/default/parse -d "{\"query\":\"okay\"}"`

**Comment by Rajskc** [comment]
@auzair92 Great! It is working..thanks a lot! How do we get to know these kind of things?

**Comment by Rajskc** [comment]
Cool. Thanks again. I am closing the issue.

**Comment by auzair92** [comment]
Glad to know that! Hit-and-trial, for the most part, I guess. Like, we could see that `GET` is working but not `POST`, so it must be something with the request that's gone wrong. And then further narrowing it down from there. :)
