### ISSUE TITLE
Discord Channel Input/ Output

### ISSUE THREAD

**Issue by Aliyss** [RasaHQ/rasa_core#745]
**Rasa Core version**:
0.98

**Python version**: 
3.6

**Operating system** (windows, osx, ...):
Windows

**Feature Request**:
I would appreciate it a lot if there were a way we could also use Discord as a channel in the channels folder. It would be a great addition.

**Comment by akelad** [comment]
If there's an API for Discord this is possible, feel free to create a PR for this :)

**Comment by MatheusFaria** [comment]
I was taking a look at this issue. It turns out that discord has an API, but it does not have a Outgoing Webhook system. Since the current channel architecture listens the incoming messages through an HTTP connections, I think that there is no standard way of implementing this connector.

Do you guys know how should be implemented a connector where the service does not emit outgoing webhooks?

**Comment by akelad** [comment]
Hmm how exactly does the API work then?

**Comment by MatheusFaria** [comment]
You need to perform a `GET` request to the `/channels/{channel.id}/messages` endpoint, which will return the messages from the channel. You can specific the `id` of the last message to get only the "unread" messages.

**Comment by akelad** [comment]
@tmbo any idea?

**Comment by MatheusFaria** [comment]
But do you think that this connector should be implemented just like the others, using the blueprint, and in the documentation we link to an extra tool that makes request to this API? Or it should not be implemented at all?
