### ISSUE TITLE
ImportError: cannot import name 'MaxTrainingError'

### ISSUE THREAD

**Issue by NikhilBansal21** [RasaHQ/rasa_core#795]
**Rasa Core version**:0.12.2

**Python version**: 3.6.5

**Operating system** (windows, osx, ...): Win 10

**Issue**: I tried running server.py  file taken from rasa_nlu master repo on running command -
python server.py -P 5000 --path projects   i am getting above stated error. I need a python script  like server.py to run my bot server. I have no expertise in python will be very grateful!

**Content of domain file** (if used & relevant):
```yaml

```

**Comment by akelad** [comment]
Can you post the exact error trace including the command you ran please?

**Comment by NikhilBansal21** [comment]
Error -  
 File "server.py", line 19, in <module>
    from rasa_nlu.data_router import (
ImportError: cannot import name 'MaxTrainingError'

It is the same server.py you guys have given in nlu repo
https://gist.github.com/NikhilBansal21/cf21f0abf143dd8d799be27b86bf917a

**Comment by akelad** [comment]
Ok, this is an NLU issue then, please post that in the nlu repo next time :) So I'm guessing you're taking the `server.py` script from our master branch, which has changed since version 0.12.2. What I would suggest is either grabbing the `server.py` from that version here: https://github.com/RasaHQ/rasa_nlu/tree/723eba889433827fd73eac4688cbeb2866b345d6
Or upgrade NLU to the latest master version.

**Comment by NikhilBansal21** [comment]
thanks the steps you told made it work! and sorry for posting it on core . Actually working on both  technologies  simultaneously  caused this

**Comment by akelad** [comment]
alright cool, i'll close this issue then!
