### ISSUE TITLE
How to stop a conversion?

### ISSUE THREAD

**Issue by sytlnrf** [RasaHQ/rasa_core#863]
**Rasa Core version**:
latest
**Python version**: 
py3.5
**Operating system** (windows, osx, ...):
ubuntu
**Issue**:
i use the api to start a conversion,but i don't know how to stop?the function in the api has PAUSE(rasa_core.events.ConversationPaused),but i don't find STOP, is the conversion effect the performance of the server if not stop?

**Content of domain file** (if used & relevant):
```yaml

```

**Comment by akelad** [comment]
what do you mean? you don't need to stop a conversation, the user can simply stop replying to the bot :)

**Comment by reza-ebrahimi** [comment]
@akelad Is there any way to break conversation flow from middle of a story and drop in another story?

**Comment by akelad** [comment]
You would have to create a story for this

**Comment by Namnt3** [comment]
Hi Guys,

On this topic, I have 1 question is that when a user asks a bot a question, the bot will answer the question in order to gather more information about the user's question, but then the user does not respond to the bot. What will bot do? As far as I understand, the bot will keep the status of this chat / story forever, right?
Is there any idea to make the bot to automatically take an action to proactively stop the conversation like: 'I've been waiting for your response for 15 minutes, please check and answer soon :)'

**Comment by akelad** [comment]
Yes, you can use the `ReminderScheduled` event. I'm gonna close this issue as this question isn't relevant to the original topic of conversation. If you need more help on how to use this event, then please post in our [forum](https://forum.rasa.com)
