### ISSUE TITLE
FormAction: Boolean slot

### ISSUE THREAD

**Issue by yuxuan2015** [RasaHQ/rasa_core#897]
When FormAction uses a Boolean slot, it will go directly to deny if an intent not in the domain file.
2018-08-24 16:49:14 DEBUG    rasa_core.featurizers  - Feature 'intent_who' (value: '1.0') could not be found in feature map. Make sure you added all intents and entities to the domain
if I add this intent to the domain, it will excute normal,why?

**Comment by amn41** [comment]
I think we'll need a bit more info in order to help you. What do you mean by "execute normal"? It would help if you provide: 
- your domain (or at least part of it)
- your stories
- what you expect to happen

also running with `rasa_core.run --debug` should provide a lot of insight  into what's happening
