### ISSUE TITLE
What is the stable version (Production Ready) for RASA CORE +  NLU + UI

### ISSUE THREAD

**Issue by bandarunagesh** [RasaHQ/rasa_core#953]
**Question**:
Can you please help me find the stable version of RASA Core, NLU and UI to use for production deployments. 

Also , i would like to know if the tensorflow NLU are ready for production?

**Comment by akelad** [comment]
Any Core/NLU releases are stable, I'd suggest using the latest ones: Core 0.11.3 and NLU 0.13.2. And yes the tensorflow version is also production ready
As for the UI, this is maintained by one of our community members, so I'm not sure about that.
Since this is more of a question for our [forum](https://forum.rasa.com), I'll close this issue. If you have further questions about this please post them there.

**Comment by m-bryo** [comment]
**Just to note**: If you're using an older CPU that doesn't support AVX, `tensorflow > 1.5` wouldn't work for you which in turn wouldn't allow you to use `rasa_core > 0.8` and `rasa_nlu > 0.11`.
If the latest rasa stack doesn't work for you, consider using `rasa_core==0.8.*`, `rasa_nlu==0.11.*` and `tensorflow==1.5.*`
